export const courses = [
    {
        course_id: 1,
        course_name: 'Java course',
        course_price: 400,
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.asjdahsjdhajksd',
        create_time: '2005-08-09T18:31:42.000+02:00',
        rating: 4,
        creator_id: 1,
        image: 'http://elearning-reskill.eu/pluginfile.php/99/course/overviewfiles/products-online-courses.png',
    },
    {
        course_id: 2,
        course_name: 'Comp science course',
        image: 'https://img-cdn.inc.com/image/upload/w_1920,h_1080,c_fill/images/panoramic/getty_1187833318_2000133220009280118_mbtvwq.jpg',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 700,
        rating: 3,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 3,
        course_name: 'JavaScript course',
        image: 'https://bexruz.ru/uploads/post/photo_1627044170515_e67644f5db151bd5ba6a8528bc6c06ce.jpg',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 400,
        rating: 1,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 4,
        course_name: 'Node JS course',
        image: 'http://rusfocus.com/wp-content/uploads/2017/10/Best-Online-Course-Providers.jpg',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 900,
        rating: 5,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 5,
        course_name: 'Mongo DB course',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSokFzau8ua3K41ExMnW-Zx8RWv16WMOo1-sK5DeuzLQo5UlEOnIcfn0R-zLTcIRdUfRSI&usqp=CAU',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 500,
        rating: 2,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 6,
        course_name: 'Python course',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhgdCaSqs5PSV_85EU2oEXtmcV1_09PqV6kBTQet7agc6CRtvM9vJAprx0AyqmLIHkdNY&usqp=CAU',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 650,
        rating: 3,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 7,
        course_name: 'Express JS course',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPb7BY-kMQ_Ez1LLW4D-pnwJaSbwujRE5snQfoIYfE8DeJfptt6hE81YbW-YS6is7ETaw&usqp=CAU',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 1000,
        rating: 5,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 8,
        course_name: 'PostgreSQL DB course',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYgtZLcjkmlInZmezPgmlzJ-ag5yjrTgnT3w&usqp=CAU',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 300,
        rating: 2,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
    {
        course_id: 9,
        course_name: 'TypeScript course',
        image: 'https://img-cdn.inc.com/image/upload/w_1920,h_1080,c_fill/images/panoramic/getty_1187833318_2000133220009280118_mbtvwq.jpg',
        course_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, perferendis aspernatur quod molestias, quae dolor iure voluptatum ut eius hic dicta blanditiis unde aliquid possimus at nemo, numquam voluptatibus quidem.',
        course_price: 750,
        rating: 4,
        create_time: '2005-08-09T18:31:42.000+02:00',
        creator_id: 1,
    },
];

export const getCourseById = (id: number) => {
    return courses.filter(course => course.course_id === id)
}